# Generated by Django 5.2.8 on 2026-01-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('wallet', 'Mobile Wallet (E-Dahab/Zaad)')], default='cash', max_length=10),
        ),
    ]
