# Generated by Django 5.2.8 on 2026-01-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_remove_order_stock_deducted_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock_deducted',
        ),
    ]
